config/routes.rb
Cyberdyne::Application.routes.draw do
  resources :targets

  resources :calls do
    collection do
      get :next
    end
  end

  match 'sign_in'  => 'user_sessions#new',     as: :sign_in

  match 'sign_out' => 'user_sessions#destroy', as: :sign_out

  resources :user_sessions, only: [:new, :create, :destroy]

  resources :users

  namespace :twilio do
    resources :calls do
      collection do
        post 'pickup_from_queue'
        get 'dequeued'
        post 'dequeued'
      end
      member do
        post 'hold'
        post 'goodbye'
        post 'user_call'
        post 'phone_number_call'
      end
    end
  end

  root to: 'home#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    can :manage, User
    can :manage, Target
    can :manage, Call
  end
end

app/models/call.rb
class Call < ActiveRecord::Base
  attr_accessible :phone_number, :state, :user, :call_sid

  belongs_to :user

  after_create :initiate!, if: :uninitiated?

  state_machine initial: :uninitiated do
    before_transition any => :connect_to_user, :do => :find_user_to_call, :unless => :user?

    before_transition :queued => :connected do |call, transition|
      call.user = User.find_by_call_sid(transition.args.first[:user_call_sid])
    end

    before_transition :connect_to_user => :connected do |call, transition|
      call.user.picked_up_call!(call_sid: transition.args.first[:user_call_sid])
    end

    before_transition :connect_to_phone_number => :connected do |call, transition|
      call.call_sid = transition.args.first[:call_sid]
    end

    before_transition any - :goodbye => :goodbye do |call, transition|
      call.user.hung_up! if call.user.present?
    end

    after_transition :queued => :connected do |call|
      call.user.picked_up_call!
    end

    after_transition any => :call_user, :do => :make_call_to_user

    event :initiate do
      transition :uninitiated => :call_user, :if => :user?
      transition :uninitiated => :connect_to_user, :if => :known_phone_number?, :unless => :user?
      transition :uninitiated => :queued, :unless => [:known_phone_number?, :user?]
    end

    event :dequeued do
      transition :queued => :connected
    end

    event :user_connected do
      transition :connect_to_user => :connected
      transition :call_user => :connect_to_phone_number
    end

    event :phone_number_connected do
      transition :connect_to_phone_number => :connected
    end

    event :call_disconnected do
      transition all - :goodbye => :goodbye
    end
  end

  protected

  def known_phone_number?
    @_known_phone_number ||= Target.where(phone_number: phone_number).any?
  end

  def make_call_to_user
    self.user.picked_up_call!(call_sid: TwilioService.make(self).sid)
  end

  def find_user_to_call
    self.user = User.first
  end

  def user?
    self.user.present?
  end
end

app/models/target.rb
class Target < ActiveRecord::Base
  attr_accessible :email, :name, :phone_number, :priority, :image_url
end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessible :name, :email, :password, :password_confirmation, :phone_number, :call_sid

  authenticates_with_sorcery!

  validates :email,
            presence: true,
            email: true

  validates :password,
            presence: true,
            length: { minimum: 6 },
            confirmation: true,
            if: :password

  has_many :calls

  state_machine initial: :available do
    before_transition any - :waiting => :waiting do |user|
      user.call_sid = TwilioService.make_queue_pickup_call_to(user.phone_number).sid
    end

    before_transition any - :available => :available do |user|
      user.call_sid = nil
    end

    before_transition any - :on_a_call => :on_a_call do |user, transition|
      unless user.call_sid.present?
        user.call_sid = transition.args.first[:call_sid]
      end
    end

    after_transition any => any do |user|
      data = { state: user.state, user_id: user.id }
      unless user.calls.empty? or user.calls.last.goodbye?
        data.merge!(call: user.calls.last.as_json)
      end
      begin
        Pusher.trigger(['userStates'], 'cyberdyne:userStateChanged', data)
      rescue Pusher::Error
      end
    end

    event :pickup_from_queue do
      transition all => :waiting
    end

    event :picked_up_call do
      transition all => :on_a_call
    end

    event :hung_up do
      transition all => :available
    end
  end
end

app/models/user_session.rb
class UserSession
  include ActiveAttr::BasicModel
  include ActiveAttr::MassAssignment

  attr_accessor :email, :password, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Uncomment to require auth on all actions (and opt-out when necessary).
  # before_filter :require_login, except: [:not_authenticated]

  protect_from_forgery
  check_authorization

  protected

  def not_authenticated
    redirect_to sign_in_path, alert: "Please sign in first."
  end

end

app/controllers/calls_controller.rb
class CallsController < ApplicationController
  before_filter :require_login

  load_and_authorize_resource

  def create
    @call = Call.new(params[:call])
    @call.user = current_user
    if @call.save!
      render json: @call
    else
      head :error
    end
  end

  def next
    current_user.pickup_from_queue!
    head :ok
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :require_login
  skip_authorization_check

  def index
  end
end

app/controllers/targets_controller.rb
class TargetsController < ApplicationController
  before_filter :require_login

  load_and_authorize_resource

  def index
  end
end

app/controllers/twilio/calls_controller.rb
class Twilio::CallsController < ApplicationController
  skip_before_filter :require_login
  skip_authorization_check
  before_filter :load_call, except: [:create]

  def create
    @call = Call.create(phone_number: params[:From], call_sid: params[:CallSid])
    render_call_state
  end

  def hold
  end

  def pickup_from_queue
  end

  def dequeued
    @call.dequeued!(user_call_sid: params[:DequeingCallSid])
    render_call_state
  end

  def user_call
    @call.user_connected!(user_call_sid: params[:CallSid])
    render_call_state
  end

  def phone_number_call
    @call.phone_number_connected!(call_sid: params[:CallSid])
    render_call_state
  end

  def goodbye
    @call.call_disconnected!
  end

  private

  def render_call_state
    render @call.state
  end

  def load_call
    @call = if params[:id] 
              Call.find(params[:id])
            elsif params[:CallSid]
              Call.find_by_call_sid(params[:CallSid])
            end
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  skip_before_filter :require_login, except: [:destroy]
  skip_authorization_check

  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(params[:user_session])

    if @user = login(@user_session.email, @user_session.password, @user_session.remember_me)
      redirect_back_or_to :targets, notice: "Successfully signed in."
    else
      flash.now[:alert] = "Sign in failed."
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to :sign_in, notice: "Signed out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :require_login

  load_and_authorize_resource

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    if @user.update_attributes(params[:user])
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def alert_class(alert_type)
    alert_type = {
      alert: 'error',
      notice: 'info'
    }.fetch(alert_type, alert_type.to_s)
    "alert-#{alert_type}"
  end

end

app/helpers/targets_helper.rb
require 'avatar/view/action_view_support'

module TargetsHelper
  include Avatar::View::ActionViewSupport
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.slim
.hero-unit
  h1 Hello, World!
  p
    | Shhh, we're in stealth mode. Just be assured we're planning the
    | future of
    '
    strike robot
    '
    | man-kind. Find out more by calling us at
    '
    strong
      | (818) 465-5104
    |. We look forward to
    '
    strike terminating
    '
    | taking your call!

app/views/layouts/application.html.slim
doctype 5
html
  head
    title Cyberdyne
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    script src="http://js.pusher.com/1.12/pusher.min.js"
    = csrf_meta_tag

  body id=(controller.controller_name) class=(controller.action_name) data-pusher-key=(Pusher.key) data-user-id=(current_user ? current_user.id : nil)
    .wrapper
      .container
        header.navbar.navbar-fixed-top
          nav.navbar-inner
            .container
              .brand
                a(href='/')
                  img src='/images/cyberdyne.png' align='bottom'
                  | Cyberdyne Systems
              ul.nav.pull-right
                - if current_user
                  li
                    form.navbar-form.form-inline
                      .input-append.input-prepend#call
                        span.add-on
                          i.icon-phone
                        input#number type='text'
                        button.btn.make-call#dial type='button' Dial
                      '
                      button.btn#next-customer type='button' Next Target
                  li.dropdown
                    a.dropdown-toggle href='#' data-toggle='dropdown'
                      = current_user.email
                      b.caret
                    ul.dropdown-menu
                      li= link_to 'Sign Out', sign_out_path
                - else
                  li= link_to 'Sign in', sign_in_path

        - flash.each do |name, msg|
          = content_tag :div, raw(msg), class: "alert #{alert_class(name)}"

        = yield

      .push

    footer
      .container
        p &copy; 2012 All rights reserved.

app/views/targets/index.html.slim
div.page-header
  h1 Targets

table.table.table-striped
  thead
    tr
      th ID
      th Image
      th Name
      th Actions

  tbody
  - @targets.each do |target|
    tr class=('error' if target.priority?)
      td= link_to target.id, target_path(target)
      td
        - if target.image_url.present?
          img(src=target.image_url)
      td= target.name
      td
        - if target.phone_number.present?
          a.call.btn.btn-primary href="tel:#{target.phone_number}"
            i.icon-phone
            '
            | Call
            '
        = link_to 'Terminate', target_path(target), method: :delete, data: { confirm: 'Terminate the target?' }, class: 'btn btn-danger'

= link_to 'New Target', new_target_path, class: 'btn btn-primary'

app/views/user_sessions/new.html.slim
= simple_form_for(@user_session) do |f|
  = f.error_notification

  .form-inputs
    = f.input :email, placeholder: 'jdoe@example.com', autofocus: true
    = f.input :password

  .form-actions
    = f.button :submit, 'Sign In', class: 'btn btn-primary'

app/views/users/_form.html.slim
= simple_form_for(@user) do |f|
  = f.error_notification

  .form-inputs
    = f.input :email, autofocus: true
    = f.input :name

  .form-actions
    = f.button :submit, class: 'btn btn-primary'
    '
    = link_to 'Back', users_path, class: 'btn'

app/views/users/edit.html.slim
.page-header
  h1 Editing user

== render 'form'

app/views/users/index.html.slim
div.page-header
  h1 Listing users

table.table.table-striped
  thead
    tr
      th ID
      th Email
      th Name
      th Actions

  tbody
  - @users.each do |user|
    tr
      td= link_to_if can?(:show, user), user.id, user_path(user)
      td= user.email
      td= user.name
      td
        - if can? :edit, user
          = link_to 'Edit', edit_user_path(user), class: 'btn btn-mini'
          '
        - if can? :destroy, user
          = link_to 'Destroy', user_path(user), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-mini btn-danger'

- if can? :create, User
  = link_to 'New User', new_user_path, class: 'btn btn-primary'

app/views/users/new.html.slim
.page-header
  h1 Create user

== render 'form'

app/views/users/show.html.slim
.page-header
  h1 User

dl
  dt Email
  dd= @user.email
  dt Name
  dd= @user.name

- if can?(:edit, @user)
  = link_to 'Edit', edit_user_path(@user), class: 'btn'
  '
= link_to 'Back', users_path, class: 'btn'

- if can?(:destroy, @user)
  '
  = link_to'Destroy', user_path(@user), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger'